config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin, constraints: AdminConstraint.new do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorship
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  scope :all_by_tags, lambda { |tags|
    questions = includes(:user)
    questions = if tags
                  questions.joins(:tags).where(tags: tags).preload(:tags)
                else
                  questions.includes(:question_tags, :tags)
                end

    questions.order(created_at: :desc)
  }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsAnswers
  before_action :require_authentication, except: %i[show index]
  before_action :set_question!, only: %i[show destroy edit update]
  before_action :authorize_question!
  after_action :verify_authorized

  def show
    load_question_answers
  end

  def destroy
    @question.destroy
    flash[:success] = t('.success')
    redirect_to questions_path
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = t('.success')
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @tags = Tag.where(id: params[:tag_ids]) if params[:tag_ids]
    @pagy, @questions = pagy Question.all_by_tags(@tags)
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      flash[:success] = t('.success')
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_question!
    @question = Question.find params[:id]
  end

  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: question %>

<%= form_with model: question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :tags %>
    </div>

    <div class="col-sm-10">
      <%= f.collection_select :tag_ids, question.tags, :id, :title, {}, multiple: true,
        class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
    </div>
  </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<article class="card my-3">
  <section class="card-header">
    <%= question.user.gravatar %>
    <%= question.user.name_or_email %>
  </section>

  <div class="card-body">
    <h4><%= link_to question.title, question_path(question) %></h2>

    <section class="card-text">
      <%= tag.time datetime: question.formatted_created_at do %>
        <small><%= question.formatted_created_at %></small>
      <% end %>

      <div class="my-2">
        <%= render question.tags %>
      </div>

      <p class="my-2">
        <%= truncate strip_tags(question.body), length: 150, omission: t('global.text.omission') %>
      </p>
    </section>

    <%= link_to t('global.button.show'), question_path(question), class: 'btn btn-primary' %> 
    
    <% if policy(question).edit? %>
      <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-secondary' %>
    <% end %>

    <% if policy(question).destroy? %>
      <%= link_to t('global.button.delete'), question_path(question), class: 'btn btn-danger',
        data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
    <% end %>
  </div>
</article>

app/views/questions/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t '.title' %></h1>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<section class="mb-5">
  <h2><%= t '.search_by_tags' %></h2>

  <%= form_with url: questions_path, method: :get do |f| %>
    <div class="mb-3">
      <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {selected: params[:tag_ids]},
        multiple: true, required: true,
        class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
    </div>

    <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
  <% end %>
</section>

<% if policy(:question).new? %>
  <%= link_to t('.new'), new_question_path, class: 'btn btn-primary btn-lg mb-3' %>
<% end %>

<%= pagination @pagy %>

<%= render @questions %>

<%= pagination @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <%= sanitize @question.body %>
</div>

<div class="mb-3">
  <%= @question.user.gravatar %>
  <%= @question.user.name_or_email %>
</div>

<%= render 'comments/commentable', commentable: @question, comment: @comment,
  html_id: 'questionComments' %>

<div class="border-top border-bottom py-3 mt-3">
  <div class="btn-group">
    <% if policy(@question).edit? %>
      <%= link_to t('global.button.edit'), edit_question_path(@question), class: 'btn btn-secondary' %>
    <% end %>

    <% if policy(@question).destroy? %>
      <%= link_to t('global.button.delete'), question_path(@question), class: 'btn btn-danger',
        data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
    <% end %>
  </div>
</div>

<h2 class="my-3"><%= t '.write_answer' %></h2>

<%= render 'answers/form' %>

<h2 class="mt-5 mb-3"><%= t '.answers' %></h2>

<%= pagination @pagy %>

<%= render partial: 'answers/answer', collection: @answers,
  as: :answer, locals: {question: @question} %>

<%= pagination @pagy %>