config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin, constraints: AdminConstraint.new do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Recoverable
  include Rememberable

  enum role: { basic: 0, moderator: 1, admin: 2 }, _suffix: :role

  attr_accessor :old_password, :admin_edit

  has_secure_password validations: false

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? && !admin_edit }
  validates :password, confirmation: true, allow_blank: true,
                       length: { minimum: 8, maximum: 70 }

  validates :email, presence: true, uniqueness: true, email: true
  validate :password_complexity
  validates :role, presence: true

  before_save :set_gravatar_hash, if: :email_changed?

  def guest?
    false
  end

  def author?(obj)
    obj.user == self
  end

  private

  def set_gravatar_hash
    return if email.blank?

    hash = Digest::MD5.hexdigest email.strip.downcase
    self.gravatar_hash = hash
  end

  def digest(string)
    cost = if ActiveModel::SecurePassword
              .min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'is incorrect'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    msg = 'complexity requirement not met. Length should be 8-70 characters and ' \
          'include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
    errors.add :password, msg
  end

  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :require_authentication
    before_action :set_user!, only: %i[edit update destroy]
    before_action :authorize_user!
    after_action :verify_authorized

    def index
      respond_to do |format|
        format.html do
          @pagy, @users = pagy User.order(created_at: :desc)
        end

        format.zip do
          UserBulkExportJob.perform_later current_user
          flash[:success] = t '.success'
          redirect_to admin_users_path
        end
      end
    end

    def create
      if params[:archive].present?
        UserBulkImportJob.perform_later create_blob, current_user
        flash[:success] = t '.success'
      end

      redirect_to admin_users_path
    end

    def edit; end

    def update
      if @user.update user_params
        flash[:success] = t '.success'
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      flash[:success] = t '.success'
      redirect_to admin_users_path
    end

    private

    def create_blob
      file = File.open params[:archive]
      result = ActiveStorage::Blob.create_and_upload! io: file,
                                                      filename: params[:archive].original_filename
      file.close
      result.key
    end

    def set_user!
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(
        :email, :name, :password, :password_confirmation, :role
      ).merge(admin_edit: true)
    end

    def authorize_user!
      authorize(@user || User)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: %i[edit update]
  before_action :set_user!, only: %i[edit update]
  before_action :authorize_user!
  after_action :verify_authorized

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t '.success'
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      flash[:success] = t('.success', name: current_user.name_or_email)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def set_user!
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation,
                                 :old_password)
  end

  def authorize_user!
    authorize(@user || User)
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper
    def user_roles
      User.roles.keys.map do |role|
        [t(role, scope: 'global.user.roles'), role]
      end
    end
  end
end

app/views/admin/users/_form.html.erb
<%= render 'shared/errors', object: user %>

<%= form_with model: [:admin, user] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>

    <div class="col-sm-10">
      <%= f.email_field :email, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :role %>
    </div>

    <div class="col-sm-10">
      <%= f.select :role, user_roles, {}, class: 'form-select form-select-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <% t_key = (user.new_record? ? "register" : "save") %>
  <%= f.submit t(t_key, scope: 'users.global.forms'), class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <th scope="row"><%= user.id %></th>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= user.created_at %></td>
  <td>
    <%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-secondary' %>
    <%= link_to 'Delete', admin_user_path(user), class: 'btn btn-danger',
      data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.users') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.users') %>

<h1 class="mb-4"><%= t '.title' %></h1>

<div class="btn-group mb-3">
  <%= link_to t('.download_zipped'), admin_users_path(format: :zip),
    class: 'btn btn-secondary', data: {confirm: t('global.dialog.you_sure')} %>
</div>

<%= pagination @pagy %>

<% scope = 'activerecord.attributes.user' %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t 'name', scope: scope %></th>
      <th scope="col"><%= t 'email', scope: scope %></th>
      <th scope="col"><%= t 'role', scope: scope %></th>
      <th scope="col"><%= t 'created_at', scope: scope %></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

<%= pagination @pagy %>

<h2 class="mb-3"><%= t '.upload_zipped' %></h2>

<%= form_with url: admin_users_path do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :archive, t('.upload_form.archive') %>
    </div>

    <div class="col-sm-10">
      <%= f.file_field :archive, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('.upload_form.submit'), class: 'btn btn-primary' %>
<% end %>